# Generated by Django 3.0.2 on 2020-05-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('des1', models.TextField()),
                ('img', models.ImageField(upload_to='pic/')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('addrss', models.TextField()),
                ('hotel_img', models.ImageField(upload_to='pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Ppd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('places', models.IntegerField()),
                ('img', models.ImageField(upload_to='pic/')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookperson', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=36)),
                ('bookdate', models.DateField()),
                ('paymentAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paymentCardNo', models.CharField(max_length=16)),
                ('companyName', models.CharField(default='company', max_length=30)),
                ('location', models.CharField(default='location', max_length=30)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('bookingday', models.DateField()),
            ],
        ),
    ]
