# Generated by Django 3.0.2 on 2020-05-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='bookingday',
            field=models.DateField(null=True),
        ),
    ]
