# Generated by Django 3.0.2 on 2020-05-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0002_auto_20200503_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='bookingId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
