# Generated by Django 3.0.2 on 2020-05-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0003_transactionhistory_bookingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
