# Generated by Django 3.0.2 on 2020-05-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0007_remove_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='dummy_check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='dummy_check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
